//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sendega.com.sendega.smsc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smsc.sendega.com/Content", ConfigurationName="com.sendega.smsc.ContentSoap")]
    public interface ContentSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/SendMms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sendega.com.sendega.smsc.SendResult SendMms(string username, string password, double destination, int pricegroup, string subject, string messageText, string dlrUrl, string extID, string refID, string imageUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/SendMms", ReplyAction="*")]
        System.Threading.Tasks.Task<Sendega.com.sendega.smsc.SendResult> SendMmsAsync(string username, string password, double destination, int pricegroup, string subject, string messageText, string dlrUrl, string extID, string refID, string imageUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sendega.com.sendega.smsc.SendResult Send(
                    string username, 
                    string password, 
                    string sender, 
                    string destination, 
                    int pricegroup, 
                    int contentTypeID, 
                    string contentHeader, 
                    string content, 
                    string dlrUrl, 
                    int ageLimit, 
                    string extID, 
                    string sendDate, 
                    string refID, 
                    int priority, 
                    int gwID, 
                    int pid, 
                    int dcs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<Sendega.com.sendega.smsc.SendResult> SendAsync(
                    string username, 
                    string password, 
                    string sender, 
                    string destination, 
                    int pricegroup, 
                    int contentTypeID, 
                    string contentHeader, 
                    string content, 
                    string dlrUrl, 
                    int ageLimit, 
                    string extID, 
                    string sendDate, 
                    string refID, 
                    int priority, 
                    int gwID, 
                    int pid, 
                    int dcs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/RequestNumberEnquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sendega.com.sendega.smsc.NumberEnquiryResult RequestNumberEnquiry(string username, string password, double msisdn, string returnUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/RequestNumberEnquiry", ReplyAction="*")]
        System.Threading.Tasks.Task<Sendega.com.sendega.smsc.NumberEnquiryResult> RequestNumberEnquiryAsync(string username, string password, double msisdn, string returnUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/SetOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SetOperator(string username, string password, decimal msisdn, short mcc, short mnc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.sendega.com/Content/SetOperator", ReplyAction="*")]
        System.Threading.Tasks.Task SetOperatorAsync(string username, string password, decimal msisdn, short mcc, short mnc);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.sendega.com/Content")]
    public partial class SendResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid messageIDField;
        
        private string errorMessageField;
        
        private int errorNumberField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.sendega.com/Content")]
    public partial class NumberEnquiryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private int errorNumberField;
        
        private double msisdnField;
        
        private string cityField;
        
        private string zipField;
        
        private string address2Field;
        
        private string address1Field;
        
        private string surnameField;
        
        private string firstnameField;
        
        private System.Guid messageIDField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("Msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("Firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContentSoapChannel : Sendega.com.sendega.smsc.ContentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentSoapClient : System.ServiceModel.ClientBase<Sendega.com.sendega.smsc.ContentSoap>, Sendega.com.sendega.smsc.ContentSoap {
        
        public ContentSoapClient() {
        }
        
        public ContentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sendega.com.sendega.smsc.SendResult SendMms(string username, string password, double destination, int pricegroup, string subject, string messageText, string dlrUrl, string extID, string refID, string imageUrl) {
            return base.Channel.SendMms(username, password, destination, pricegroup, subject, messageText, dlrUrl, extID, refID, imageUrl);
        }
        
        public System.Threading.Tasks.Task<Sendega.com.sendega.smsc.SendResult> SendMmsAsync(string username, string password, double destination, int pricegroup, string subject, string messageText, string dlrUrl, string extID, string refID, string imageUrl) {
            return base.Channel.SendMmsAsync(username, password, destination, pricegroup, subject, messageText, dlrUrl, extID, refID, imageUrl);
        }
        
        public Sendega.com.sendega.smsc.SendResult Send(
                    string username, 
                    string password, 
                    string sender, 
                    string destination, 
                    int pricegroup, 
                    int contentTypeID, 
                    string contentHeader, 
                    string content, 
                    string dlrUrl, 
                    int ageLimit, 
                    string extID, 
                    string sendDate, 
                    string refID, 
                    int priority, 
                    int gwID, 
                    int pid, 
                    int dcs) {
            return base.Channel.Send(username, password, sender, destination, pricegroup, contentTypeID, contentHeader, content, dlrUrl, ageLimit, extID, sendDate, refID, priority, gwID, pid, dcs);
        }
        
        public System.Threading.Tasks.Task<Sendega.com.sendega.smsc.SendResult> SendAsync(
                    string username, 
                    string password, 
                    string sender, 
                    string destination, 
                    int pricegroup, 
                    int contentTypeID, 
                    string contentHeader, 
                    string content, 
                    string dlrUrl, 
                    int ageLimit, 
                    string extID, 
                    string sendDate, 
                    string refID, 
                    int priority, 
                    int gwID, 
                    int pid, 
                    int dcs) {
            return base.Channel.SendAsync(username, password, sender, destination, pricegroup, contentTypeID, contentHeader, content, dlrUrl, ageLimit, extID, sendDate, refID, priority, gwID, pid, dcs);
        }
        
        public Sendega.com.sendega.smsc.NumberEnquiryResult RequestNumberEnquiry(string username, string password, double msisdn, string returnUrl) {
            return base.Channel.RequestNumberEnquiry(username, password, msisdn, returnUrl);
        }
        
        public System.Threading.Tasks.Task<Sendega.com.sendega.smsc.NumberEnquiryResult> RequestNumberEnquiryAsync(string username, string password, double msisdn, string returnUrl) {
            return base.Channel.RequestNumberEnquiryAsync(username, password, msisdn, returnUrl);
        }
        
        public void SetOperator(string username, string password, decimal msisdn, short mcc, short mnc) {
            base.Channel.SetOperator(username, password, msisdn, mcc, mnc);
        }
        
        public System.Threading.Tasks.Task SetOperatorAsync(string username, string password, decimal msisdn, short mcc, short mnc) {
            return base.Channel.SetOperatorAsync(username, password, msisdn, mcc, mnc);
        }
    }
}
